[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "5ead0ec4eb9321819b5e09a497af801ab676fd5a"
os = "macos"

    [[LLVMLibUnwind.download]]
    sha256 = "f22f4701fb84cf849ddf5c9e0f4559ccc529b1538118a76f9a8d7c03de69276a"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.aarch64-apple-darwin.tar.gz"
[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "c955e59fbf3409600d39fe62429f3b5d130603b0"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "6047cc0c3df74894e5eda095577f84a5ff272693d369148f0092c7b34b85f000"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.aarch64-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "15a5226a64f07e4817d14d13bc25677f0c12efb8"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "adb95b179bcfb702b8897ea310f1fefe088651264956f6642cc98db23b6f4648"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.aarch64-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "82b066f200bd97fca78bf4c85a0cd64262e49dbd"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "ea0353a326f91924284daee0abd62d293c6b75f7562ff89a19c7da14149ac581"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.armv6l-linux-gnueabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d074834af92e59e50d3b22552f3eab625e6ff3d"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "4efa62281015c51a76e9cf17dff8f673a4792a24f142136ed792f6ec93bbdf92"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.armv6l-linux-musleabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d3acd57003b1d9b1fc9f758e59e519572702cbf1"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "f84a1fd5c0a9b3a1b42ad918ea3b4f52e19eff3975189a5ea35c33cabe2fbcaa"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ea75ba06d13809ebda851fdee2fbff68a773977b"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "20a40944dba1607e3adfeb888368c945bc2b9519c54459e048cfe5ab3e832653"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.armv7l-linux-musleabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "044d5278c0547d95f1110222b8fa7ecea0ac224a"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "bd99055fb4ced794ae51a7f52a0d7c8fe2063a895276b9d563527607922e5099"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.i686-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "e918cc967e9111a57270db0a0195ec332057124d"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "f76c1d3650109527dc7edf634cbf426913438705421a991a9a7ce130d1b3ca1f"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.i686-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "da5c03bc9f169c4940357972d7a031ac5ccc1429"
os = "windows"

    [[LLVMLibUnwind.download]]
    sha256 = "5efcb247188090c83237df9e22d439b23237b493be2a879b045c59c15feb35c7"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.i686-w64-mingw32.tar.gz"
[[LLVMLibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "262c70a725f12ca04fd18086d1ddc7d083c82cb3"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "40227a0c89a1c0b7bb8cc680b9677c83b79e9637f527042eedf5890c6936964f"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.powerpc64le-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "035c6a0426d9a67fa554c235f0471a20ac2ce809"
os = "macos"

    [[LLVMLibUnwind.download]]
    sha256 = "ad2d0b896fcb2435cd54ce7bde02a061b516e287134cb59d522f3800f175aed6"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.x86_64-apple-darwin.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "485314776661a7a93cc13dcf3886ac38db6d3133"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "161c80bf9fb0facd8ea20efc61b8db85d8afe22eea8f5dc49991fcd85fd30d36"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.x86_64-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "10d08e334bb5bc7b2112d25b6fa782df9e66bc83"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "29c54e7bc554105aeaddf3938375c5921f4b236f708d49053c14d85731add765"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.x86_64-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "9552cc676c7eedeaf1ff30ab585e144788e18bc6"
os = "freebsd"

    [[LLVMLibUnwind.download]]
    sha256 = "35975d08d4314915ef3e6dafe6ba42059151e91b0642bd76783e184db4673cbd"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.x86_64-unknown-freebsd.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "3f8dc718271d0a95880a1a5ccad7fee1ec454dd5"
os = "windows"

    [[LLVMLibUnwind.download]]
    sha256 = "164da0518fa944179a67c16ea29a06dec21c0361a2018bef84a6f12c2982dc52"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+2/LLVMLibUnwind.v11.0.0.x86_64-w64-mingw32.tar.gz"
