[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "af7caafb4ee1854c3ab40846e6e41a79cdb2a1c5"
os = "macos"

    [[LLVMLibUnwind.download]]
    sha256 = "30b99207bfe29612dc75b75011548f09c68605c1c1fd4aab14b87c00fd30f9a4"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.aarch64-apple-darwin.tar.gz"
[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "e9a3864d9b2e305d1225f7e329e4559b527051d4"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "4a09982319f38d37e77f5fdd903d84dbb527c0d5c0a4bd4b101cab13429fa735"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.aarch64-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "115ee9eefbd243e481534cd60ea95a9d2686814e"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "eeaa990c8c4ce3b71cda7900698b9aee4a77fd910794e84af0cfe5bf60eea675"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.aarch64-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6c0b317fa3564fc981fb937c1103c31a2f2c30ef"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "38c891b1ea35aa553236d1bcb60d7fb4ff8377d47a54ebceb11d14e4f78092df"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.armv6l-linux-gnueabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8fcc21df251e6eae40edb61557fb2225f2bf34cf"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "01950958eecd730ea901c0efef5dcadc53812b5c1fd08ed61c6da9d0cba25698"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.armv6l-linux-musleabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "78c535ae4df271a810896cff9a88da6a8554b42c"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "53cdd4d751147ec1151377552916a8ae61b3a820906f899e775b02b834f04559"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8098258690eb6195f9be09e79899a294bc0f66b7"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "db83c925f52b0ddf7f8b5d05540dcdc2655138c193089b2c22b4c7d888ace1d3"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.armv7l-linux-musleabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "34f38a1b3df711ab5a6999c1a7b5f13678c03329"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "30502ce1fcc05e1362d97dbb0aa78e440d13e937c3859cdef9ff633995cf89ad"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.i686-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "8bd194ea093e8ad274c8b8500ebf934222b1ea6b"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "d955240178e5a73a725cec5e446b8c8b6b8ce4e01150e51f0d9a2b2ce7b5f3b4"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.i686-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "5da708e921368e1d4ae2e6066b70d8753c4465d3"
os = "windows"

    [[LLVMLibUnwind.download]]
    sha256 = "86331c1029169545fe5cc55cc1184cec51ec66254bc395f56a30f4905383e821"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.i686-w64-mingw32.tar.gz"
[[LLVMLibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "4abe39b74870f99edd61550efa83cdcd1fc992a9"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "a953b287137592916cef080cb69ba1da283d34604356e3a56dc7187e4ca393a9"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.powerpc64le-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "5763261ee47a69345e34b2d051fa3d40cf3468f9"
os = "macos"

    [[LLVMLibUnwind.download]]
    sha256 = "07be7c7014a744fd62a5724c6a02d97d6110a465be27c8f6cb8cbc71208ae97b"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.x86_64-apple-darwin.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "bc1f6a0c18efeb87e49258c972a0455c904f6e30"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "73dceb2bc92234ad2b893f9b48cc12c096a878ff634c592bc4fd7f37f0a2f960"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.x86_64-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "bc159ff33742766aec4a4830d39e47e8dbcd8abe"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "8babb570836ddbdafd8830811493ffa30b088e707082a2bc2048ac865aa83703"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.x86_64-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "75158fef9bca16c65ebcd83d38f58f7d9a51784d"
os = "freebsd"

    [[LLVMLibUnwind.download]]
    sha256 = "4cb88a28f5d5c9f4f6f5ea2b88cb0b7ad40184b913e09f402c9b2d34c846189e"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "e047ba747e7577c3e7919982bbfc8ae5a5fe8d92"
os = "windows"

    [[LLVMLibUnwind.download]]
    sha256 = "ac8510f119e0ec6ba5f022f63bb77539b9a63ea6ad0baa50f41a95a62523f60c"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+1/LLVMLibUnwind.v11.0.1.x86_64-w64-mingw32.tar.gz"
