[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "867c14b6cc9ee13d5453acf73b01d83e7650f52d"
os = "macos"

    [[LLVMLibUnwind.download]]
    sha256 = "6348ce8cde0309ce87d024f5ca7b09c7e32e1827338a7aa221cec136db5e84b1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.aarch64-apple-darwin.tar.gz"
[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "099f49253f4a24c6ea61b79a04072a8e972de4e9"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "3786f616ad50e4bce519fe5933b18588c546f1815e22e63ff42360ba4caa1728"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.aarch64-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "e9014186a322d472d7658e25870490352107dc16"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "4fe165a9a2f8a1fbca0f1e5ddcf2f300f2e9e3b932b5b53ec02bdff26f31c9cb"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.aarch64-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "f64a2f681adb1951b827386f6b5f9cb3e621e070"
os = "freebsd"

    [[LLVMLibUnwind.download]]
    sha256 = "64e7585ef393312b830d7f5718eed9d56502441552ae529700e4101e128b2205"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.aarch64-unknown-freebsd.tar.gz"
[[LLVMLibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "36a57c187eaa36157b7980add9efa3ec4b9f1b8a"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "565edcaf83816fb1f6d9f27371b6a9f7b64f409abaf458ed03c2d5ef8e959051"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.armv6l-linux-gnueabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "374393434b41097e3af4c3e3eb56df482555e2da"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "eeb268323a101edef8fc2ad562e70795644442bc658d7b83e79ff1206a8eb578"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.armv6l-linux-musleabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3a608cef007bc341fd9430e8afbce1893c943682"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "24f497890c991d3ab57e5ef07151c40c9f44f5f8fe27669ab71dcda302c7f3ce"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b7e194dcdbd18e3827a41b06b7aa0b494633dccf"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "9f95c68a8e72d41e4dd2795dfae8bb2bf15add59b0299ba40ea5e7fb42802ed6"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.armv7l-linux-musleabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "02bad0632a59baebb3a5864a07919ec125119483"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "77b2afddf96a461fed617a69083032a98ba2bce2c380abb573bfd80f4f301587"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.i686-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "6f18956b0f147194fc30446b8226789ae96d6ff2"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "6fb8c254d43d4d396fb6e27effae5a76be1ff83839d70f91563e519740a94f17"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.i686-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "be289b3f868d4d768b9d3802a96a1594120f2b37"
os = "windows"

    [[LLVMLibUnwind.download]]
    sha256 = "9b33c15e729aaa762a32fabb9dee40a2c64727d7ccd233a814ebb9401666bd98"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.i686-w64-mingw32.tar.gz"
[[LLVMLibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "1c396c5821b0180a97c9eccffd514542d8a00364"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "bff1cc33a0d31be0d131093cd01a0b8408619ff0232f0f7f5785cdaee91b0d4f"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.powerpc64le-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "27ebe32abcff496097eafaf38e3d6027536dadec"
os = "macos"

    [[LLVMLibUnwind.download]]
    sha256 = "1e6710be59c0b57878e191b6767bbab2d5ccb5f099a99379a8af4d4c95b8a27d"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.x86_64-apple-darwin.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "10fffe849ec5161d2597366cac53a48822bbcad2"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "310952ad92afcbfd37b821def81a43a121fe9f44e86dfdb5c4b9cb806abf0dd0"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.x86_64-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "4b68d59454b7d9604952422a2a09e451173a200f"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "8af6f2e5230628771176c6e3e5ba225fae6a305ddb88ce41c3e786c4f9725ae8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.x86_64-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "1f0faa16f25f5c914ca56ed144526a473c78d4d2"
os = "freebsd"

    [[LLVMLibUnwind.download]]
    sha256 = "0104e7bc3aa5e355fd03ae18a328a477d07be235ff7d330450e06d11669a0c8b"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.x86_64-unknown-freebsd.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "4cf9b9e24a200f335c850a188bf44fbc36822999"
os = "windows"

    [[LLVMLibUnwind.download]]
    sha256 = "6d621d3dc5d10b2d68817bf2010de374702f66bd2fe1ed6b48253078979e66c5"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v18.1.7+0/LLVMLibUnwind.v18.1.7.x86_64-w64-mingw32.tar.gz"
