[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "6e54f0a1b666fd83fa965b9a8575e51fa3546217"
os = "macos"

    [[LLVMLibUnwind.download]]
    sha256 = "9c8d47114de82a4ea404522f68d2670e2182808e9a7f6175d2548803889e86cc"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.aarch64-apple-darwin.tar.gz"
[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "7700644ff8ec2b0ce74f167d2ccea8695ca10bcb"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "9aeb49ddde7774288f7ad97ec26d644d4c92165d66cc90e666d067e05e931d8d"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.aarch64-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "7580066dc47e0c84b27d4c6a2d44eaf6abb307ca"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "365bb4c9574adb448cdf9837d14cdeb709f0f379d7b4e45be875c72933b0a265"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.aarch64-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8d4ba214345d15445e67ae10873265ca59c81b2a"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "8f37eec81dc41d04aeaae5bf90e75d6957b9a7b3542c16f4201f94d189c7991c"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.armv6l-linux-gnueabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d9b0a9c9364df1376acb3680c741a4d0aafbda5b"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "313be1b49a1efb474e8b64ab252114685aee302f7fc2e78eca0284cac1f01e4c"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.armv6l-linux-musleabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0b05463084f6bf57bcb05710408c019565f6b30e"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "51615dab81aec39f7cf1686dff0a7159868c6717d8414d444f5f1faa544cca10"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d36563f53f25f14cf106b20b6a16630792806494"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "90ecc52e7e41600c26cda18a64cb9c4f828cedac0a28828b0d923cbc26c0b0be"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.armv7l-linux-musleabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "5d0e37db37223ad1fa6b8f6e9156b28943b7cf3f"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "7254f06f1dba3d2ba5d2456119e670ade464fabb4b44ec7666efe36ca40e4568"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.i686-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "cb5484e25bad45bd9a4095363ea4e3d6a1816a8a"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "4ecc21b45252bbdf126d6651e1d5aacea8c25429f44e99ae2ddb1f4bd32558bb"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.i686-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "0e092b1c67435864d9751bf64249cf74db1bbde2"
os = "windows"

    [[LLVMLibUnwind.download]]
    sha256 = "46be6fea7175be77bf0d6399c9e582dee9cb3c53887012dddfcb3d55800fe9fc"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.i686-w64-mingw32.tar.gz"
[[LLVMLibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "e61c868e40f582ae66dcfcd23bba025cc9cd9204"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "b6d4a0fc3747b18e43f2a034493fbe485ef217a6ac1ecaf560b4a892cf119022"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.powerpc64le-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "e65d65a86ecbbfe622bfc53bca25380090f4496d"
os = "macos"

    [[LLVMLibUnwind.download]]
    sha256 = "0aa56e663d0a7eea36bbc27c606763eaacff9ba8052954eb3ebd33506c158e2b"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.x86_64-apple-darwin.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "fcedaef92baf8e1dd73a078c9f39bc8df712835d"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "b7a2819462495d00e6d5effd0f8a09497d1e0d83538c76235694654e53c5af03"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.x86_64-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "ffb0e4c7f2383b9a458d0f343b0e2818c49027fd"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "a011d56f8591120ec3478154df822b9a3bcce93651fa2c1de8339569b8a0abe6"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.x86_64-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "5f2920aaef1f5497923d6242741ee0952561874a"
os = "freebsd"

    [[LLVMLibUnwind.download]]
    sha256 = "b9bc210ff2a92e9ff9dd870867c9f325e18a5078f99e675cdce1a75ccdaa260d"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "a1dc4eb6bfde33b33bd9979cfeff51ed8b342235"
os = "windows"

    [[LLVMLibUnwind.download]]
    sha256 = "c4983f8ff130999a43191913a568f66f1aad47923bad5d76b83aad6134955127"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.1+0/LLVMLibUnwind.v11.0.1.x86_64-w64-mingw32.tar.gz"
