[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "fa29c20b237ea5f9a193ff60cbe1b4c38d8c9af2"
os = "macos"

    [[LLVMLibUnwind.download]]
    sha256 = "979a54f5336868d4c7ba63c8a839ca8efdc232d23c4569830d8dc05df3b26174"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.aarch64-apple-darwin.tar.gz"
[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "8c7a0a28e18ba16f4535576b5f34cd90cc270bcb"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "104ec1a973868184768d7c6b3704f6b9fc65ce383e5b48d81b8838843e6874b1"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.aarch64-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "aarch64"
git-tree-sha1 = "52ff58d5ca19c6f1b6a8324e2dd4f9c0b84c26d5"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "92a374234df59a347b6f9a1a2346c0f02876120758ad52f85a7fa803c0edc3c3"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.aarch64-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3446e9ed0be329905cd2bbfa8506320cb1577490"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "d25230a9836f03eaa9c0c9586183e4116636b631898c1e7beaa85ae1f295b689"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.armv6l-linux-gnueabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6be1ba829141a63ae1cede1b1aa80db0787d0895"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "7682c8e52fb59e9cfe2fadf2774ca1270e46fcbde03a0039f76100df270b8b62"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.armv6l-linux-musleabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d986c7b3c168f11f27fa1a4c7f06e0be597cab6d"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "2ffa58f7704dbbee64813dce0dca4ebccbf80affad60a9d88719a2fdd1e3916d"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.armv7l-linux-gnueabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "129c76445d9ff9b686dae258637c502fef3425c7"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "b2a7557d945049497ec6ac8ccc117d2e1cf1e8f1ed2924d4046dca69df0af759"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.armv7l-linux-musleabihf.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "88a1b38628c2ec2a4986efa4df862e3dbfaf9a6b"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "974cd540f0a81980ead1066bd375bcf88f6cb7bd33131fa39d45c91d756243e0"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.i686-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "b2456604dcc83571eaecea17cbad1f28e5ce3c33"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "76ff88cb5ba7d6d985a0befc98bb17fc9ffa5134319a50480b34fcc03a0ade8e"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.i686-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "i686"
git-tree-sha1 = "5ac0bf4f0af8a859878de35ed7419ac30db74170"
os = "windows"

    [[LLVMLibUnwind.download]]
    sha256 = "d8783fa7eac6bc0daaec6f1aee1906e7c6884b8210768902bfcbab1bad5f9766"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.i686-w64-mingw32.tar.gz"
[[LLVMLibUnwind]]
arch = "powerpc64le"
git-tree-sha1 = "7b62b5eb0d2d1893181193363fb824282d4c547a"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "983a7fc092b420fba87c51c8ff29f7984ef983769e55eb37cc14482e40d6319f"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.powerpc64le-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "4abdbebc1016039c07c620f139f04270bfeb3299"
os = "macos"

    [[LLVMLibUnwind.download]]
    sha256 = "cabce4353a3849e160a99e9f3babfb35b452487aaf1a151e06c013be800e2259"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.x86_64-apple-darwin.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "dce3b30566264d289c5e6f309ec7942c64cf8437"
libc = "glibc"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "8246332f386d9956c2757cc701ab11361b3e15143aab0c07f0be348b945c77ec"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.x86_64-linux-gnu.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "8bd0652ed9a2f6d3e31851e905179e98d6dad118"
libc = "musl"
os = "linux"

    [[LLVMLibUnwind.download]]
    sha256 = "92b75fec335c8540769af475ee9546922391f90ba4559b3846d8a9f7ff2c52ee"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.x86_64-linux-musl.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "7e21c3cddf6e196bba7089f8545d2fd36fa56b32"
os = "freebsd"

    [[LLVMLibUnwind.download]]
    sha256 = "fb342f2995ff723dc8da37ab3a85ee3cb30a89d436145dfb9d0bf61b7310d1e8"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.x86_64-unknown-freebsd.tar.gz"
[[LLVMLibUnwind]]
arch = "x86_64"
git-tree-sha1 = "7f42f63f55b39cae9ce078810a6d8780d651ac80"
os = "windows"

    [[LLVMLibUnwind.download]]
    sha256 = "00516665eb002ee180ca523ac8bda175a72b490bcf3315a755bb6a1011fd17e4"
    url = "https://github.com/JuliaBinaryWrappers/LLVMLibUnwind_jll.jl/releases/download/LLVMLibUnwind-v11.0.0+1/LLVMLibUnwind.v11.0.0.x86_64-w64-mingw32.tar.gz"
