# Autogenerated wrapper script for LLVMLibUnwind_jll for aarch64-apple-darwin
export libunwind

JLLWrappers.@generate_wrapper_header("LLVMLibUnwind")
JLLWrappers.@declare_library_product(libunwind, "@rpath/libunwind.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libunwind,
        "lib/libunwind.1.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
