# Autogenerated wrapper script for LLVMLibUnwind_jll for i686-w64-mingw32
export libunwind

JLLWrappers.@generate_wrapper_header("LLVMLibUnwind")
JLLWrappers.@declare_library_product(libunwind, "libunwind.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libunwind,
        "bin\\libunwind.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
